### (G_NA)
GET http://localhost:3000/api/v1/sessions

### (G2)
GET http://localhost:3000/api/v1/users

### (G3yn)
GET http://localhost:3000/api/v1/votes/is_ready

### (G4)
GET http://localhost:3000/api/v1/users/status

### (G4yn)
GET http://localhost:3000/api/v1/votes/is_finished

### G5
GET http://localhost:3000/api/v1/ideas/winners

### (G6)
GET http://localhost:3000/api/v1/votes

### (G7)
GET http://localhost:3000/api/v1/ideas


