### (G_NA)
GET http://localhost:3000/api/v1/sessions

### (G2)
GET http://localhost:3000/api/v1/users

### (G7)
GET http://localhost:3000/api/v1/ideas

### (G6)
GET http://localhost:3000/api/v1/votes

### (G4)
GET http://localhost:3000/api/v1/users/status